export enum EACTIONS {
    LOGGED_IN = "LOGGED_IN",
    LOGGED_OUT = "LOGGED_OUT",
    CHANGE_APP_FLAG = "CHANGE_APP_FLAG",
    SET_TOKEN = "SET_TOKEN",
    REMOVE_TOKEN = "REMOVE_TOKEN",
    SET_AUTHENTICATION = 'SET_AUTHENTICATION',
    REMOVE_AUTHENTICATION = 'REMOVE_AUTHENTICATION',
    SET_NETWORK_STATUS = 'SET_NETWORK_STATUS',
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    UPDATE_CART_ITEM = 'UPDATE_CART_ITEM',
    CLEAR_CART = 'CLEAR_CART',
}