export enum EACTIONS {
    LOGGED_IN = "LOGGED_IN",
    LOGGED_OUT = "LOGGED_OUT",
    CHANGE_APP_FLAG = "CHANGE_APP_FLAG",
    SET_TOKEN = "SET_TOKEN",
    REMOVE_TOKEN = "REMOVE_TOKEN",
    SET_AUTHENTICATION = 'SET_AUTHENTICATION',
    REMOVE_AUTHENTICATION = 'REMOVE_AUTHENTICATION',
    SET_NETWORK_STATUS = 'SET_NETWORK_STATUS',
    ADD_TO_CART = 'ADD_TO_CART',
    REMOVE_FROM_CART = 'REMOVE_FROM_CART',
    UPDATE_CART_ITEM = 'UPDATE_CART_ITEM',
    CLEAR_CART = 'CLEAR_CART',

    SET_LIBRARY_VIEW = 'SET_LIBRARY_VIEW',
    SET_LIBRARY_DATA = 'SET_LIBRARY_DATA',
    SET_LIBRARY_VERSION = 'SET_LIBRARY_VERSION',
    CLEAR_LIBRARY = 'CLEAR_LIBRARY',

    SET_COLLECTION_VIEW = 'SET_COLLECTION_VIEW',
    SET_COLLECTION_DATA = 'SET_COLLECTION_DATA',
    CLEAR_COLLECTION = 'CLEAR_COLLECTION',

    SET_SYNC = 'SET_SYNC',
    RESET_SYNC = 'RESET_SYNC',

    RESET_DOWNLOADING_BOOK_FILE = 'RESET_DOWNLOADING_BOOK_FILE',
    UPDATE_DOWNLOADING_BOOK_FILE = 'UPDATE_DOWNLOADING_BOOK_FILE',
}
