export const ar = {
    login: "تسجيل الدخول",
    register: "تسجيل",
    sign_in: 'تسجيل الدخول',
    app_title: 'متجر الكتب',
    app_title_: 'عنوان التطبيق',
    app_logo: 'متجر الكتب',
    brand_name: 'متجر الكتب',
    sign_in_bookstore_account: 'تسجيل الدخول باستخدام حساب متجر الكتب الخاص بك',
    forgot_password: 'هل نسيت كلمة مرورك؟',
    msg: {
        ui: {
            msg1: 'عملیات با موفقیت انجام شد.',
            msg2: 'خطا رخ داد.',
            msg3: 'ثبت نام با موفقیت انجام شد، به صفحه ورود منتقل می شوید.',
            msg4: 'رمز عبور با موفقیت تغییر کرد، به صفحه ورود منتقل می شوید.',
            your_rate_submited: 'رتبه شما ثبت شد',
            your_comment_submited: 'نظر شما ثبت شد',
            your_comment_will_be_removed_continue: 'نظر شما حذف خواهد شد، تایید می کنید؟',
            no_network_connection: 'خطا رخ داد، لطفا دسترسی اینترنت خود را بررسی کرده و مجددا تلاش کنید.',
            new_vesion_available_update: 'نسخه جدیدی از برنامه موجود است، می توانید بروز کنید.',
            item_will_be_removed_continue: 'رکورد مورد نظر حذف خواهد شد، تایید می کنید؟',
            your_purchase_completed: 'خرید شما تکمیل شد',
            your_collection_will_be_removed_continue: 'حذف کلکسیون کتاب های موجود در آن را حذف نخواهد کرد.',
            your_collection_will_be_downloaded_continue: 'همه کتاب های این کلکسیون دانلود می شود.',
            file_could_not_be_uploaded: 'فایل قابل آپلود نیست.',
            one_img_upload_allowed_remove_existing_one: "تنها می توانید یک تصویر بارگذاری کنید لطفا عکس فعلی را حذف کنید.",
            login_again: 'مجددا وارد شوید',
            sync_error: 'هنگام همگام سازی خطایی روی داد',
            logout_erase_user_data_warning: 'با خروج از برنامه، همه اطلاعات این کاربر، از این دستگاه حذف می شود.',
        },
        back: {
            user_already_exists: 'کاربر از قبل وجود دارد.',
            no_valid_activation_code: 'کد فعالسازی شما منقضی شده است، برای دریافت کد جدید ارسال مجدد را بفشارید.',
            wrong_activation_code: 'کد فعالسازی اشتباه است.',
            already_has_valid_key: 'امکان ارسال مجدد پیامک {0} ثانیه دیگر برای شما فعال می شود.',
            message_not_sent: 'ارسال پیامک با خطا مواجه شد، لطفا مجددا تلاش کنید.',
            cell_no_required: 'تلفن همراه الزامی است.',
            message_sent: 'پیام با موفقیت برای تلفن همراه ارسال شد.',
            username_exists: 'نام کاربری تکراری است، لطفا نام کاربری دیگری انتخاب کنید.',
            signup_token_not_exists: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            invalid_signup_token: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            token_invalid: 'مجددا وارد شوید',
            token_expired: 'token expired',
            delete_failed: 'deleting failed',
            get_failed: 'getting failed',
            auth_decoding_failed: 'Authentication decoding failed',
            commit_failed: 'commiting to database failed',
            no_auth: 'no auth found',
            invalid_username: 'نام کاربری یا رمز عبور اشتباه است.',
            invalid_enum: 'enum is not correct  type',
            not_found: 'entity not found',
            invalid_persons: 'there is invalid person id in list',
            addition_error: 'adding model to database failed',
            username_cellno_required: 'برای دریافت رمز عبور نام کاربری یا شماره موبایل را وارد کنید',
            invalid_user: "با اطلاعات وارد شده کاربری وجود ندارد",
            invalid_code: 'کد تایید اشتباه است.',

            filter_required: 'filter object is not in data',
            upload_failed: 'uploading files encountered a problem',
            invalid_entity: 'entity is not right instance of Class',
            access_denied: 'user has not access to this action',
            already_liked: 'user already liked this comment',
            comment_not_found: 'comment not found',
            already_reported: ' user already reported the comment',
            report_not_found: 'report by this user for this comment not found',
            parent_not_found: 'parent object cant found',
            follow_denied: 'user cant follow him/her self',
            already_follows: 'user already follows target',
            missing_requiered_field: 'missing requiered field',
            already_rated: 'user already rated to book',
            already_exists: 'entity already exists',
            credit_debit_error: 'credit and debit can not have amount at the same time',
            no_price_found: 'there is no price for this book in our tables',
            discount_is_float: 'discount should be sent in float format',
            insufficiant_balance: 'your account value is lower than your reciept',
            user_has_no_account: 'user has no account',
            order_invoiced: 'order is invoiced and not deletable',
            commit_error: 'error while commiting in db',
            person_has_books: 'person already has roles for books',
            book_not_in_lib: 'کتاب در کتابخانه شما وجود ندارد و نمی توان آن را به کلکسیونی افزود.',
            online_book_count_limitation: 'فقط کتاب چاپی و DVD تعداد بیشتر از 1 می پذیرد.',
        }
    },
    validation: {
        minLength: 'حداقل {value} کاراکتر',
        mobileFormat: 'فرمت موبایل صحیح نیست',
        smsCodeFormat: 'فرمت کد صحیح نیست.',
        confirmPassword: 'رمز عبور با تایید آن همخوانی ندارد.',
        emailFormat: 'فرمت ایمیل صحیح نیست',
        phoneFormat: 'فرمت تلفن صحیح نیست',
    },
    username: 'نام کاربری',
    password: 'رمز عبور',
    name: 'نام',
    lastname: 'نام خانوادگی',
    phone: 'تلفن',
    address: 'آدرس',
    mobile: 'تلفن همراه',
    email: 'ایمیل',
    confirm_password: 'تایید رمز عبور',
    invalid_value: 'مقدار نامعتبر است',
    required_field: 'فیلد ضروری است',
    Show_password: 'نمایش رمزعبور',
    login_agree_msg: {
        a: 'با انتخاب "ورود" شما موافقت خود با {0} و {1} را تایید می کنید.',
        b: 'مطالب فروشگاه کتاب',
        c: 'شرایط استفاده از نرم افزار'
    },
    new_to_Bookstore: 'تازه واردید؟',
    need_free_bookstore_account: "احتیاج به یک حساب کاربری رایگان فروشگاه کتاب دارید.",
    register_your_mobile_number: 'شماره تلفن همراه خود را وارد کنید',
    submit: 'ثبت',
    already_have_bookstore_account: 'از قبل حساب کاربری فروشگاه کتاب دارید؟',
    verification_code_sended_via_sms_submit_here: 'کد تایید برای شما پیامک شد، لطفا در اینجا ثبت کنید.',
    verification_code: 'کد تایید',
    create_an_account: 'ساخت حساب کاربری',
    send_again: 'ارسال مجدد',
    send_again_activationCode: 'ارسال مجدد کد فعالسازی',
    in: 'در',
    second: 'ثانیه',
    search: 'جستجو',
    home: 'خانه',
    library: 'کتابخانه',
    store: 'فروشگاه',
    more: 'بیشتر',
    recomended_for_you: 'پیشنهادی برای شما',
    new_release_in_bookstore: 'نسخه های جدید در کتابفروشی',
    more_by_writer: 'بیشتر از {0}',
    helen_hardet: 'هلن هاردت',
    it_will_be_launched_soon: 'بزودی راه اندازی خواهد شد.',

    read_now: 'الان بخوان',
    view_in_store: 'نمایش در فروشگاه',
    add_to_collection: 'اضافه کردن به کلکسیون',
    mark_as_read: 'به عنوان خوانده شده علامت بزن',
    share_progress: 'اشتراک گذاری پیشرفت',
    recommend_this_book: 'پیشنهاد دادن کتاب',
    remove_from_device: 'حذف از دستگاه',
    remove_from_home: 'حذف از خانه',
    loading_with_dots: 'درحال بارگذاری...',
    retry: 'تلاش مجدد',
    title: 'عنوان',
    return: 'بازگشت',
    insert_username_or_mobile: 'نام کاربری یا تلفن همراه خود را وارد کنید',
    reset_password: 'تغییر رمز عبور',
    add_to_list: 'به لیست اضافه کن',
    log_out: 'خروج',
    sync: 'همگام سازی',
    syncing: 'در حال همگام سازی',
    syncing_with_dots: 'در حال همگام سازی...',
    last_synced_on: 'آخرین همگام سازی در',
    read_listen_with_audible: 'خواندن و گوش دادن با صدا',
    book_update: 'بروزرسانی کتاب',
    reading_insights: 'خواندن عمیق',
    settings: 'تنظیمات',
    info: 'اطلاعات',
    help_feedback: 'کمک و بازخورد',
    about_bookstore_edition: 'درباره نسخه کتابفروشی',
    Length: 'اندازه',
    pages: 'صفحه',
    from_the_editor: 'از ویرایشگر',
    about_this_item: 'درباره این محصول',

    description: 'توضیحات',
    product_description: 'توضیحات محصول',
    review: 'نظر',
    reviews: 'نظرات',
    review_s: 'نظر',
    about_the_author: 'درباره نویسنده',
    features_details: 'ویژگی ها و جزئیات',
    product_details: 'جزئیات محصول',
    publication_date: 'تاریخ انتشار',
    publisher: 'ناشر',
    language: 'زبان',
    bookstore_sales_rank: 'رتبه فروش در کتابفروشی',
    follow: 'دنبال کردن',
    unfollow: 'دنبال نکردن',
    customer_review: 'نظر مشتری ها',
    customer_vote_s: 'رای مشتری ها',
    read_reviews_that_mention: 'خواندن نظر های ذکر شده',
    see_more: 'بیشتر ببینید',
    see_less: 'کمتر ببینید',
    top_reviews: 'نظر های برتر',
    verified_purchase: 'خرید تایید شده',
    format: 'قالب',
    bookstore_edition: 'نسخه کتابفروشی',
    people_found_this_helpful: 'نفر این مورد را مفید یافتند',
    people_found_this_helpful_1: 'نفر این مورد را مفید یافت',
    people_report_this: 'نفر این مورد را گزارش کردند',
    people_report_this_1: 'نفر این مورد را گزارش کرد',
    helpful: 'مفید است',
    report: 'گزارش',
    see_all_n_reviews: 'دیدن همه {0} نظر',
    write_a_review: 'یک نظر بگذارید',
    n_out_of_m_stars: '{0} از {1} ستاره',
    bookstore_books: 'کتاب های کتابفروشی',
    best_seller: 'پرفروش ها',
    more_to_explore: 'بیشتر برای کاوش',
    all: 'همه',
    downloaded: 'دانلود شده',
    more_reviews: 'نظرات بیشتر',
    thank_you_for_your_feedback: 'با تشکر از بازخورد شما',
    inspired_by_your_wishlist: 'با توجه به لیست علاقه مندی ها شما',
    uncollected: 'بدون دسته',
    of: 'از',
    from: 'از',
    to: 'تا',
    customer_reviews: 'نظرات مشتری ها',
    by_writerName: 'از',
    agent: 'نماینده',
    previous: 'قبلی',
    next: 'بعدی',
    no_item_found: 'موردی یافت نشد',
    category: {
        category: 'گروه',
        new: 'نسخه ها جدید',
        best_seller: 'پرفروش ها',
        recommended: 'پیشنهادی برای شما',
        wishlist: 'لیست علاقه مندی ها',

        romance: 'عاشقانه',
        classic: 'کلاسیک',
        comedy: 'کمدی',
        drama: 'درام',
        historical: 'تاریخی',
        religious: 'مذهبی',
        science: 'علمی',
        social: 'اجتماعی',
    },
    load_more: 'بارگذاری بیشتر',
    book_isben: 'شابک',
    your_comment: 'نظر شما',
    remove: 'حذف',
    your_report_submited: 'گزارش شما ثبت شد',
    vote: 'رای',
    vote_s: 'رای',
    votes: 'آراء',
    remove_from_list: 'از لیست حذف کن',
    recent_reviews: 'نظرات اخیر',
    minute: 'دقیقه',
    hour: 'ساعت',
    remove_comment: 'حذف نظر',
    close: 'بستن',
    app_info: 'اطلاعات برنامه',
    version: 'نسخه',
    version_mode: 'نوع نسخه',
    trial_mode: 'نسخه آزمایشی',
    trial: 'آزمایشی',
    dont_want_now: "فعلا نمی خواهم",
    update: 'بروزرسانی',
    shopping_cart: 'سبد خرید',
    remove_from_wish_list: 'از لیست علاقه مندی ها حذف کن',
    add_to_wish_list: 'به لیست علاقه مندی ها اضافه کن',
    remove_from_cart_list: 'از سبد خرید حذف کن',
    add_to_cart_list: 'به سبد خرید اضافه کن',
    your_shopping_cart_is_empty: 'سبد خرید شما خالیست',
    book_type: 'نوع کتاب',
    genre_type_list: {
        Comedy: "کمدی",
        Drama: "درام",
        Romance: "رمان",
        Social: "اجتماعی",
        Religious: "دینی",
        Historical: "تاریخی",
        Classic: "کلاسیک",
        Science: "علمی",
    },
    book_type_list: {
        DVD: 'دی وی دی',
        Audio: 'صوتی',
        Hard_Copy: 'چاپی',
        Pdf: 'پی دی اف',
        Epub: 'Epub'
    },
    role_type_list: {
        Author: 'مولف',
        Writer: 'نویسنده',
        Translator: 'مترجم',
        Press: 'مطبوعات',
        Contributer: 'مشارکت کننده',
        Designer: 'طراح',
    },
    buy: 'خرید',
    price: 'قیمت',
    total_price: 'قیمت کل',
    recalculate: 'محاسبه مجدد',
    view_detail: 'نمایش جزئیات',
    cancel: 'انصراف',
    ok: 'تایید',
    create: 'ایجاد',
    new_collection: 'کلکسیون جدید',
    collection_name: 'نام کلکسیون',
    create_new_collection: 'ایجاد کلکسیون جدید',
    remove_collection: 'حذف کلکسیون',
    delete_collection_: 'کلکسیون حذف شود؟',
    rename_collection: 'تغییر نام کلکسیون',
    rename: 'تغییر نام',
    download_collection: 'دانلود کلکسیون',
    download_collection_: 'کلکسیون دانلود شود؟',
    download: 'دانلود',
    add: 'افزودن',
    selected: 'انتخاب شده',
    select_all: 'انتخاب همه',
    deselect_all: 'لغو انتخاب همه',
    profile: "پروفایل",
    profile_image: "تصویر پروفایل",
    exist_in_library: 'موجود در کتابخانه',
    preview: "پیش نمایش",
    drag_and_drop: "drag and drop",
    choose_image: 'انتخاب تصویر',
    n_min_left_in_chapter: '{0} دقیقه از فصل مانده است',
    book_from_your_library: 'کتاب از کتابخانه شما',
    your_recent_item_appear_manage_remove: 'کتاب اخیر شما در اینجا ظاهر می شود. شما می توانید آن را در هر زمان مدیریت یا حذف کنید. ',
    go_to_library: 'رفتن به کتابخانه',
    shop_in_store: 'خرید از فروشگاه',
    sure_you_want_log_out: 'آیا برای خروج از برنامه مطمئن هستید؟',
    readed_: 'خوانده شده',
    close_book: 'بستن کتاب',
    goto: 'برو به',
    go: 'برو',
    enter_location: 'مکان را وارد کنید',
    you_are_reading_loaction_n: 'شما اکنون مکان {0} را می خوانید.',
    purchase_history: 'تاریخچه خرید',
    purchase_date: 'تاریخ خرید',
    page_not_found: 'صفحه یافت نشد',
    detail: 'جزئیات',
    count: 'تعداد',
    unit_price: 'قیمت واحد',
    type: 'نوع',
}