export const en = {
    login: "login",
    register: "register",
    sign_in: 'sign in',
    app_title: 'book store',
    app_logo: 'bookstore',
    sign_in_bookstore_account: 'sign in with your bookstore account',
    forgot_password: 'forgot password?',
    msg: {
        ui: {
            msg1: 'action succeeded',
            msg2: 'error occurred',
            msg3: 'registered successfully, we redirect you to login page.',
        },
        back: {
            msg1: 'user already exists',
            msg2: 'your activation code has expired, please click resend to reseive new one.',
            msg3: 'activation code is invalid',
            msg4: 'sending sms will active for you in {0} second',
            msg5: 'error occuerd while sending sms, please try again.',
            msg6: 'cell number is required',
            msg7: 'message sent to cell number successfully',
            msg8: 'username already exists.please choose another one',
            msg9: 'Your registration has expired, please start the registration process from the beginning.',
            msg10: 'Your registration has expired, please start the registration process from the beginning.',

            msg11: 'token invalid',
            msg12: 'token expired',
            msg13: 'deleting failed',
            msg14: 'getting failed',
            msg15: 'Authentication decoding failed',
            msg16: 'commiting to database failed',
            msg17: 'no auth found',
            msg18: 'username or password is not valid',
        }
    },
    validation: {
        minLength: 'min length {value} character',
        mobileFormat: 'mobile format is not valid',
        smsCodeFormat: 'code is not valid.',
        confirmPassword: 'confirm password not match password.',
    },
    username: 'username',
    password: 'password',
    name: 'name',
    lastname: 'last name',
    phone: 'phone',
    address: 'address',
    mobile: 'mobile',
    confirm_password: 'confirm password',
    invalid_value: 'invalid value',
    required_field: 'required field',
    Show_password: 'Show password',
    login_agree_msg: {
        a: 'By tapping "Sign in" you agree to the {0} {1}',
        b: 'Bookstore Content',
        c: 'and Software Terms of Use'
    },
    new_to_Bookstore: 'new to Bookstore?',
    need_free_bookstore_account: "You'll need a free Bookstore account to sign in.",
    register_your_mobile_number: 'Register your mobile number',
    submit: 'submit',
    already_have_bookstore_account: 'already have bookstore account?',
    verification_code_sended_via_sms_submit_here: 'verification code sended via sms, submit here.',
    verification_code: 'verification code',
    create_an_account: 'create an account',
    send_again: 'send again',
    in: 'in',
    second: 'second',
}