export const en = {
    login: "login",
    register: "register",
    sign_in: 'sign in',
    app_title: 'book store',
    app_logo: 'bookstore',
    sign_in_bookstore_account: 'sign in with your bookstore account',
    forgot_password: 'forgot password?',
    msg: {
        msg1: 'action succeeded',
        msg2: 'error occurred',
        msg3: 'registered successfully, we redirect you to login page.',
    },
    validation: {
        minLength: 'min length {value} character',
        mobileFormat: 'mobile format is not valid',
        smsCodeFormat: 'code is not valid.',
        confirmPassword: 'confirm password not match password.',
    },
    username: 'username',
    password: 'password',
    name: 'name',
    lastname: 'last name',
    phone: 'phone',
    address: 'address',
    mobile: 'mobile',
    confirm_password: 'confirm password',
    invalid_value: 'invalid value',
    required_field: 'required field',
    Show_password: 'Show password',
    login_agree_msg: {
        a: 'By tapping "Sign in" you agree to the {0} {1}',
        b: 'Bookstore Content',
        c: 'and Software Terms of Use'
    },
    new_to_Bookstore: 'new to Bookstore?',
    need_free_bookstore_account: "You'll need a free Bookstore account to sign in.",
    register_your_mobile_number: 'Register your mobile number',
    submit: 'submit',
    already_have_bookstore_account: 'already have bookstore account?',
    verification_code_sended_via_sms_submit_here: 'verification code sended via sms, submit here.',
    verification_code: 'verification code',
    create_an_account: 'create an account',
}