export const fa = {
    login: "ورود",
    register: "ثبت نام",
    sign_in: 'ورود',
    app_title: 'فروشگاه کتاب',
    app_logo: 'فروشگاه کتاب',
    sign_in_bookstore_account: 'با حساب فروشگاه کتاب خود داخل شوید',
    forgot_password: 'رمز عبورتان را فراموش کردید؟',
    msg: {
        ui: {
            msg1: 'عملیات با موفقیت انجام شد.',
            msg2: 'خطا رخ داد.',
            msg3: 'ثبت نام با موفقیت انجام شد، به صفحه ورود منتقل می شوید.',
        },
        back: {
            msg1: 'کاربر از قبل وجود دارد.',
            msg2: 'کد فعالسازی شما منقضی شده است، برای دریافت کد جدید ارسال مجدد را بفشارید.',
            msg3: 'کد فعالسازی اشتباه است.',
            msg4: 'امکان ارسال مجدد پیامک {0} ثانیه دیگر برای شما فعال می شود.',
            msg5: 'ارسال پیامک با خطا مواجه شد، لطفا مجددا تلاش کنید.',
            msg6: 'تلفن همراه الزامی است.',
            msg7: 'پیام با موفقیت برای تلفن همراه ارسال شد.',
            msg8: 'نام کاربری تکراری است، لطفا نام کاربری دیگری انتخاب کنید.',
            msg9: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',
            msg10: 'فرصت ثبت نام شما پایان یافت، لطفا مراحل ثبت نام را از ابتدا شروع کنید.',

            msg11: 'token invalid',
            msg12: 'token expired',
            msg13: 'deleting failed',
            msg14: 'getting failed',
            msg15: 'Authentication decoding failed',
            msg16: 'commiting to database failed',
            msg17: 'شما وارد نشده اید',
            msg18: 'نام کاربری یا رمز عبور اشتباه است.',
        }
    },
    validation: {
        minLength: 'حداقل {value} کاراکتر',
        mobileFormat: 'فرمت موبایل صحیح نیست',
        smsCodeFormat: 'فرمت کد صحیح نیست.',
        confirmPassword: 'رمز عبور با تایید آن همخوانی ندارد.',
    },
    username: 'نام کاربری',
    password: 'رمز عبور',
    name: 'نام',
    lastname: 'نام خانوادگی',
    phone: 'تلفن',
    address: 'آدرس',
    mobile: 'تلفن همراه',
    confirm_password: 'تایید رمز عبور',
    invalid_value: 'مقدار نامعتبر است',
    required_field: 'فیلد ضروری است',
    Show_password: 'نمایش رمزعبور',
    login_agree_msg: {
        a: 'با انتخاب "ورود" شما موافقت خود با {0} و {1} را تایید می کنید.',
        b: 'مطالب فروشگاه کتاب',
        c: 'شرایط استفاده از نرم افزار'
    },
    new_to_Bookstore: 'تازه واردید؟',
    need_free_bookstore_account: "احتیاج به یک حساب کاربری رایگان فروشگاه کتاب دارید.",
    register_your_mobile_number: 'شماره تلفن همراه خود را وارد کنید',
    submit: 'ثبت',
    already_have_bookstore_account: 'از قبل حساب کاربری فروشگاه کتاب دارید؟',
    verification_code_sended_via_sms_submit_here: 'کد تایید برای شما پیامک شد، لطفا در اینجا ثبت کنید.',
    verification_code: 'کد تایید',
    create_an_account: 'ساخت حساب کاربری',
    send_again: 'ارسال مجدد',
    send_again_activationCode: 'ارسال مجدد کد فعالسازی',
    in: 'در',
    second: 'ثانیه',
    search: 'جستجو',
    home: 'خانه',
    library: 'کتابخانه',
    store: 'فروشگاه',
    more: 'بیشتر',
    recomended_for_you: 'پیشنهادی برای شما',
    new_release_in_bookstore: 'نسخه های جدید در کتابفروشی',
    more_by_writer: 'بیشتر از {0}',
    helen_hardet: 'هلن هاردت',
    it_will_be_launched_soon: 'بزودی راه اندازی خواهد شد.',
}